# Generated by Django 3.1.7 on 2023-12-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20210303_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tanggal',
            field=models.DateField(auto_now=True),
        ),
    ]
